apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-db-deployment
spec:
  serviceName: myapp-db-service
  replicas: 1
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: myapp-db
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: myapp-db
    spec:
      containers:
        - name: myapp-database
          image: mcr.microsoft.com/mssql/server
          ports:
            - containerPort: 1433
          env:
            - name: "ACCEPT_EULA"
              value: "Y"
            - name: "SA_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD
            - name: "MSSQL_PID"
              value: "Express"
          volumeMounts:
            - name: mssqldb
              mountPath: /mssql/data
            - name: secret-volume
              mountPath: /etc/secretVolume  
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: gcp-volume-claim  
      - name: secret-volume
        secret:
          secretName: mssql 
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Delete  