// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using frontend.Models;

#nullable disable

namespace frontend.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20230619144044_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("frontend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VAT")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enabled = true,
                            Name = "Microsoft",
                            VAT = "IE8256796U"
                        },
                        new
                        {
                            Id = 2,
                            Enabled = false,
                            Name = "Google",
                            VAT = "IE6388047V"
                        },
                        new
                        {
                            Id = 3,
                            Enabled = true,
                            Name = "Nagarro",
                            VAT = "IE6383047V"
                        },
                        new
                        {
                            Id = 4,
                            Enabled = false,
                            Name = "TCS",
                            VAT = "IE6333047V"
                        },
                        new
                        {
                            Id = 5,
                            Enabled = true,
                            Name = "IBM",
                            VAT = "IE6558047V"
                        },
                        new
                        {
                            Id = 6,
                            Enabled = false,
                            Name = "Tech Mahindra",
                            VAT = "IE9281047V"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
