apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  database_uri: "Server= 10.104.128.250;Database=myapp;User=sa;Password=A&VeryComplex123Password;MultipleActiveResultSets=true;TrustServerCertificate=True"