apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-volume-claim 
spec:
  storageClassName: gcp-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi